## Statistical Approaches

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from collections import Counter
from collections import defaultdict
from sklearn.preprocessing import StandardScaler

In [6]:
df = pd.read_csv('../dataset/cmi_internet_imputed.csv')

In [7]:
num_cols = df.select_dtypes(include=np.number).columns.tolist()

X = df[num_cols].copy()

print("Numerical variables used for HBOS:")
print(num_cols)
print("Shape:", X.shape)

Numerical variables used for HBOS:
['Basic_Demos-Age', 'Basic_Demos-Sex', 'CGAS-CGAS_Score', 'Physical-Height', 'Physical-Weight', 'Physical-Waist_Circumference', 'Physical-Diastolic_BP', 'Fitness_Endurance-Max_Stage', 'Physical-HeartRate', 'Physical-Systolic_BP', 'FGC-FGC_CU', 'FGC-FGC_GSND', 'FGC-FGC_GSD', 'FGC-FGC_PU', 'FGC-FGC_SRL', 'FGC-FGC_SRR', 'FGC-FGC_TL', 'BIA-BIA_Activity_Level_num', 'BIA-BIA_BMC', 'BIA-BIA_BMR', 'BIA-BIA_ECW', 'BIA-BIA_Fat', 'BIA-BIA_Frame_num', 'BIA-BIA_ICW', 'BIA-BIA_LDM', 'BIA-BIA_LST', 'BIA-BIA_SMM', 'PAQ_Total', 'SDS-SDS_Total_T', 'PreInt_EduHx-computerinternet_hoursday', 'Fitness_Endurance-Time', 'sii']
Shape: (8460, 32)

In [8]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=num_cols,
    index=df.index
)

X_scaled.head()

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Fitness_Endurance-Max_Stage,Physical-HeartRate,Physical-Systolic_BP,...,BIA-BIA_Frame_num,BIA-BIA_ICW,BIA-BIA_LDM,BIA-BIA_LST,BIA-BIA_SMM,PAQ_Total,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday,Fitness_Endurance-Time,sii
0,-1.466005,-0.820524,-0.498013,-1.557409,-0.864848,-0.281158,0.008835,0.102005,0.474900,-0.122879,...,-1.375678,-0.147202,-0.145140,-0.237769,-0.189612,-0.180694,0.200873,1.985093,0.088778,2.128877
1,-0.346958,-0.820524,-0.031901,-1.278714,-0.987759,-1.456477,0.575087,0.102005,-1.099996,0.476246,...,-1.375678,-0.213382,-0.090231,-0.233342,-0.240660,-0.402784,0.617237,-0.969843,-0.072985,-0.607211
2,-0.067196,1.218734,0.123470,-0.094260,-0.229808,-0.286183,-0.368666,0.102005,1.123386,0.101793,...,0.443649,-0.060075,0.020440,-0.087325,-0.047041,-0.104271,-0.423672,1.000114,0.146551,-0.607211
3,-0.346958,-0.820524,0.123470,-0.163933,-0.076169,-0.281158,-0.840542,1.091641,1.401309,0.101793,...,0.443649,-0.031003,-0.073927,-0.071203,-0.103863,0.419992,-1.360491,-0.969843,1.579309,0.760833
4,2.170899,1.218734,-0.062975,0.701916,-0.193958,-0.281158,-0.085540,0.102005,-0.173587,0.026902,...,0.443649,-0.061143,-0.008977,-0.087325,-0.013130,-2.212518,-0.007309,0.015136,-0.084539,-0.607211

### Z-score method

In [9]:
#applying the Z-score method to identify outliers
from scipy import stats
z_scores = pd.DataFrame(
    stats.zscore(X, nan_policy="omit"),
    columns=num_cols,
    index=df.index
)
z_scores.head()

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Fitness_Endurance-Max_Stage,Physical-HeartRate,Physical-Systolic_BP,...,BIA-BIA_Frame_num,BIA-BIA_ICW,BIA-BIA_LDM,BIA-BIA_LST,BIA-BIA_SMM,PAQ_Total,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday,Fitness_Endurance-Time,sii
0,-1.466005,-0.820524,-0.498013,-1.557409,-0.864848,-0.281158,0.008835,0.102005,0.474900,-0.122879,...,-1.375678,-0.147202,-0.145140,-0.237769,-0.189612,-0.180694,0.200873,1.985093,0.088778,2.128877
1,-0.346958,-0.820524,-0.031901,-1.278714,-0.987759,-1.456477,0.575087,0.102005,-1.099996,0.476246,...,-1.375678,-0.213382,-0.090231,-0.233342,-0.240660,-0.402784,0.617237,-0.969843,-0.072985,-0.607211
2,-0.067196,1.218734,0.123470,-0.094260,-0.229808,-0.286183,-0.368666,0.102005,1.123386,0.101793,...,0.443649,-0.060075,0.020440,-0.087325,-0.047041,-0.104271,-0.423672,1.000114,0.146551,-0.607211
3,-0.346958,-0.820524,0.123470,-0.163933,-0.076169,-0.281158,-0.840542,1.091641,1.401309,0.101793,...,0.443649,-0.031003,-0.073927,-0.071203,-0.103863,0.419992,-1.360491,-0.969843,1.579309,0.760833
4,2.170899,1.218734,-0.062975,0.701916,-0.193958,-0.281158,-0.085540,0.102005,-0.173587,0.026902,...,0.443649,-0.061143,-0.008977,-0.087325,-0.013130,-2.212518,-0.007309,0.015136,-0.084539,-0.607211

In [10]:
#flagging outliers based on Z-score threshold (e.g., 3) and count them
z_threshold = 3
z_outliers = (z_scores.abs() > z_threshold).any(axis=1)
z_outliers.value_counts()

False    6250
True     2210
Name: count, dtype: int64

### Grubbs Test

In [11]:
def grubbs_test_one_outlier(data, alpha=0.05):
    """
    Grubbs test for one outlier in univariate data.
    
    H0: there are no outliers
    H1: there is at least one outlier
    
    Returns information about the most suspicious point.
    """
    
    data = pd.Series(data).dropna()
    
    n = len(data)
    
    if n < 3:
        return {
            "is_outlier": False,
            "index": None,
            "value": None,
            "G": np.nan,
            "G_critical": np.nan
        }
    
    mean = data.mean()
    std = data.std(ddof=1)
    
    if std == 0:
        return {
            "is_outlier": False,
            "index": None,
            "value": None,
            "G": 0,
            "G_critical": np.nan
        }
    
    # Most suspicious observation: the one farthest from the mean
    relative_values = abs(data - mean)
    outlier_index = relative_values.idxmax()
    outlier_value = data.loc[outlier_index]
    
    # Grubbs statistic
    G = relative_values.loc[outlier_index] / std
    
    # Critical value
    t = stats.t.ppf(1 - alpha / (2 * n), n - 2)
    
    G_critical = ((n - 1) / np.sqrt(n)) * np.sqrt(
        t**2 / (n - 2 + t**2)
    )
    
    is_outlier = G > G_critical
    
    return {
        "is_outlier": is_outlier,
        "index": outlier_index,
        "value": outlier_value,
        "G": G,
        "G_critical": G_critical
    }

In [12]:
X_grubbs = X_scaled.copy()

In [13]:
col = X_grubbs.columns[0]

result = grubbs_test_one_outlier(X_grubbs[col], alpha=0.05)

result

{'is_outlier': np.False_,
 'index': np.int64(997),
 'value': np.float64(3.2899467733492482),
 'G': np.float64(3.2897523263044004),
 'G_critical': np.float64(4.526965968196977)}

In [14]:
grubbs_results = []

for col in X_grubbs.columns:
    result = grubbs_test_one_outlier(X_grubbs[col], alpha=0.05)

    grubbs_results.append({
        "variable": col,
        "is_outlier": result["is_outlier"],
        "outlier_index": result["index"],
        "outlier_value_scaled": result["value"],
        "G": result["G"],
        "G_critical": result["G_critical"]
    })

grubbs_results_df = pd.DataFrame(grubbs_results)

grubbs_results_df.sort_values("G", ascending=False)

,variable,is_outlier,outlier_index,outlier_value_scaled,G,G_critical
19,BIA-BIA_BMR,True,3205,49.458409,49.455485,4.526966
23,BIA-BIA_ICW,True,3205,47.223854,47.221063,4.526966
18,BIA-BIA_BMC,True,3205,46.891559,46.888788,4.526966
26,BIA-BIA_SMM,True,3205,44.154619,44.152009,4.526966
25,BIA-BIA_LST,True,3205,38.414418,38.412147,4.526966
20,BIA-BIA_ECW,True,3205,36.667235,36.665068,4.526966
2,CGAS-CGAS_Score,True,2065,28.960264,28.958552,4.526966
24,BIA-BIA_LDM,True,3205,27.850758,27.849112,4.526966
7,Fitness_Endurance-Max_Stage,True,3767,22.863637,22.862286,4.526966
11,FGC-FGC_GSND,True,2039,15.726336,15.725407,4.526966
12,FGC-FGC_GSD,True,59,15.656102,15.655177,4.526966
10,FGC-FGC_CU,True,2027,12.418406,12.417672,4.526966
6,Physical-Diastolic_BP,True,1140,10.390114,10.389500,4.526966
30,Fitness_Endurance-Time,True,164,8.777763,8.777244,4.526966
9,Physical-Systolic_BP,True,3199,-8.660407,8.659895,4.526966
13,FGC-FGC_PU,True,2425,8.310817,8.310326,4.526966
21,BIA-BIA_Fat,True,921,7.105212,7.104792,4.526966
5,Physical-Waist_Circumference,True,632,6.770752,6.770352,4.526966
4,Physical-Weight,True,3270,5.900382,5.900033,4.526966
16,FGC-FGC_TL,True,536,5.592990,5.592660,4.526966
14,FGC-FGC_SRL,True,968,5.398170,5.397851,4.526966
8,Physical-HeartRate,True,1159,5.199587,5.199279,4.526966
27,PAQ_Total,True,4295,5.175674,5.175368,4.526966
15,FGC-FGC_SRR,True,825,4.971485,4.971191,4.526966
28,SDS-SDS_Total_T,False,51,4.364511,4.364253,4.526966
31,sii,False,76,3.496921,3.496715,4.526966
3,Physical-Height,False,3818,-3.368928,3.368729,4.526966
0,Basic_Demos-Age,False,997,3.289947,3.289752,4.526966
17,BIA-BIA_Activity_Level_num,False,12,3.155804,3.155618,4.526966
22,BIA-BIA_Frame_num,False,21,2.262976,2.262842,4.526966
29,PreInt_EduHx-computerinternet_hoursday,False,0,1.985093,1.984976,4.526966
1,Basic_Demos-Sex,False,2,1.218734,1.218661,4.526966

In [15]:
grubbs_detected = grubbs_results_df[grubbs_results_df["is_outlier"]]

grubbs_detected

,variable,is_outlier,outlier_index,outlier_value_scaled,G,G_critical
2,CGAS-CGAS_Score,True,2065,28.960264,28.958552,4.526966
4,Physical-Weight,True,3270,5.900382,5.900033,4.526966
5,Physical-Waist_Circumference,True,632,6.770752,6.770352,4.526966
6,Physical-Diastolic_BP,True,1140,10.390114,10.389500,4.526966
7,Fitness_Endurance-Max_Stage,True,3767,22.863637,22.862286,4.526966
8,Physical-HeartRate,True,1159,5.199587,5.199279,4.526966
9,Physical-Systolic_BP,True,3199,-8.660407,8.659895,4.526966
10,FGC-FGC_CU,True,2027,12.418406,12.417672,4.526966
11,FGC-FGC_GSND,True,2039,15.726336,15.725407,4.526966
12,FGC-FGC_GSD,True,59,15.656102,15.655177,4.526966
13,FGC-FGC_PU,True,2425,8.310817,8.310326,4.526966
14,FGC-FGC_SRL,True,968,5.398170,5.397851,4.526966
15,FGC-FGC_SRR,True,825,4.971485,4.971191,4.526966
16,FGC-FGC_TL,True,536,5.592990,5.592660,4.526966
18,BIA-BIA_BMC,True,3205,46.891559,46.888788,4.526966
19,BIA-BIA_BMR,True,3205,49.458409,49.455485,4.526966
20,BIA-BIA_ECW,True,3205,36.667235,36.665068,4.526966
21,BIA-BIA_Fat,True,921,7.105212,7.104792,4.526966
23,BIA-BIA_ICW,True,3205,47.223854,47.221063,4.526966
24,BIA-BIA_LDM,True,3205,27.850758,27.849112,4.526966
25,BIA-BIA_LST,True,3205,38.414418,38.412147,4.526966
26,BIA-BIA_SMM,True,3205,44.154619,44.152009,4.526966
27,PAQ_Total,True,4295,5.175674,5.175368,4.526966
30,Fitness_Endurance-Time,True,164,8.777763,8.777244,4.526966

### Likelihood Approach

In [21]:

if isinstance(X_scaled, np.ndarray):
    X_likelihood = pd.DataFrame(
        X_scaled,
        columns=num_cols,
        index=df.index
    )
else:
    X_likelihood = X_scaled.copy()

X_likelihood.head()

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Fitness_Endurance-Max_Stage,Physical-HeartRate,Physical-Systolic_BP,...,BIA-BIA_Frame_num,BIA-BIA_ICW,BIA-BIA_LDM,BIA-BIA_LST,BIA-BIA_SMM,PAQ_Total,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday,Fitness_Endurance-Time,sii
0,-1.466005,-0.820524,-0.498013,-1.557409,-0.864848,-0.281158,0.008835,0.102005,0.474900,-0.122879,...,-1.375678,-0.147202,-0.145140,-0.237769,-0.189612,-0.180694,0.200873,1.985093,0.088778,2.128877
1,-0.346958,-0.820524,-0.031901,-1.278714,-0.987759,-1.456477,0.575087,0.102005,-1.099996,0.476246,...,-1.375678,-0.213382,-0.090231,-0.233342,-0.240660,-0.402784,0.617237,-0.969843,-0.072985,-0.607211
2,-0.067196,1.218734,0.123470,-0.094260,-0.229808,-0.286183,-0.368666,0.102005,1.123386,0.101793,...,0.443649,-0.060075,0.020440,-0.087325,-0.047041,-0.104271,-0.423672,1.000114,0.146551,-0.607211
3,-0.346958,-0.820524,0.123470,-0.163933,-0.076169,-0.281158,-0.840542,1.091641,1.401309,0.101793,...,0.443649,-0.031003,-0.073927,-0.071203,-0.103863,0.419992,-1.360491,-0.969843,1.579309,0.760833
4,2.170899,1.218734,-0.062975,0.701916,-0.193958,-0.281158,-0.085540,0.102005,-0.173587,0.026902,...,0.443649,-0.061143,-0.008977,-0.087325,-0.013130,-2.212518,-0.007309,0.015136,-0.084539,-0.607211

In [22]:
def norm_dist(x, mu, sigma):
    return 1 / (np.sqrt(2 * np.pi) * sigma) * np.exp(-((x - mu) ** 2) / (2 * sigma ** 2))


def unif_dist(x, n):
    return 1 / n

In [23]:
def log_likelihood_univariate(M, A, lambda_par=0.3, eps=1e-12):
    """
    Log-likelihood for the univariate likelihood approach.

    M = observations currently treated as normal
    A = observations currently treated as anomalous
    lambda_par = prior probability of belonging to anomalous distribution
    """

    M = np.asarray(M)
    A = np.asarray(A)

    ll = 0

    if len(M) > 0:
        muM = np.mean(M)
        sigmaM = np.std(M)

        if sigmaM == 0:
            sigmaM = eps

        dens_M = norm_dist(M, muM, sigmaM)
        dens_M = np.maximum(dens_M, eps)

        ll += len(M) * np.log(1 - lambda_par)
        ll += np.sum(np.log(dens_M))

    if len(A) > 0:
        sizeA = len(A)
        dens_A = np.array([unif_dist(x, sizeA) for x in A])
        dens_A = np.maximum(dens_A, eps)

        ll += len(A) * np.log(lambda_par)
        ll += np.sum(np.log(dens_A))

    return ll

In [29]:
def likelihood_outliers_univariate(x, lambda_par=0.3, c=5):
    """
    Likelihood-based outlier detection for one numerical variable.
    """

    x = pd.Series(x).dropna()

    M = x.copy()
    A = pd.Series(dtype=float)

    outliers = []

    for idx, value in x.items():

        if idx not in M.index:
            continue

        ll_before = log_likelihood_univariate(
            M.values,
            A.values,
            lambda_par=lambda_par
        )

        M_candidate = M.drop(index=idx)
        A_candidate = pd.concat([A, pd.Series([value], index=[idx])])

        ll_after = log_likelihood_univariate(
            M_candidate.values,
            A_candidate.values,
            lambda_par=lambda_par
        )

        delta_ll = abs(ll_before - ll_after)

        if delta_ll > c:
            outliers.append({
                "index": idx,
                "value": value,
                "delta_ll": delta_ll
            })

            M = M_candidate
            A = A_candidate

    return pd.DataFrame(outliers)

In [30]:
all_likelihood_outliers = []

for col in X_likelihood.columns:
    out_col = likelihood_outliers_univariate(
        X_likelihood[col],
        lambda_par=0.3,
        c=5
    )

    if len(out_col) > 0:
        out_col["variable"] = col
        all_likelihood_outliers.append(out_col)

if len(all_likelihood_outliers) > 0:
    all_likelihood_outliers = pd.concat(all_likelihood_outliers, ignore_index=True)
else:
    all_likelihood_outliers = pd.DataFrame(
        columns=["index", "value", "delta_ll", "variable"]
    )

all_likelihood_outliers

all_likelihood_outliers

       index      value    delta_ll                variable
0        997   3.289947    5.487010         Basic_Demos-Age
1       2065  28.960264  434.045286         CGAS-CGAS_Score
2       4086  16.437389  165.405097         CGAS-CGAS_Score
3       4317  28.960264  491.380555         CGAS-CGAS_Score
4       4380  28.960264  548.484315         CGAS-CGAS_Score
...      ...        ...         ...                     ...
37372   8456   0.134996    9.190330  Fitness_Endurance-Time
37373   8457   1.013138    8.670524  Fitness_Endurance-Time
37374   8458   0.435413    9.092553  Fitness_Endurance-Time
37375   8459   0.111887    9.194909  Fitness_Endurance-Time
37376     76   3.496921    6.190323                     sii

[37377 rows x 4 columns]

In [27]:
all_likelihood_outliers["variable"].value_counts()

variable
Basic_Demos-Sex                           8460
PreInt_EduHx-computerinternet_hoursday    8460
BIA-BIA_SMM                               8460
BIA-BIA_LST                               8460
BIA-BIA_LDM                               8460
BIA-BIA_ICW                               8460
BIA-BIA_Frame_num                         8460
BIA-BIA_ECW                               8460
BIA-BIA_BMR                               8460
BIA-BIA_BMC                               8460
FGC-FGC_TL                                8459
BIA-BIA_Fat                               8459
BIA-BIA_Activity_Level_num                8459
sii                                       8459
CGAS-CGAS_Score                           8459
Physical-Height                           8459
Basic_Demos-Age                           8458
Physical-HeartRate                        8457
Physical-Waist_Circumference              8457
FGC-FGC_SRL                               8457
FGC-FGC_PU                                8457
Fitness_Endurance-Max_Stage               8456
Physical-Weight                           8456
FGC-FGC_GSD                               8456
FGC-FGC_CU                                8454
SDS-SDS_Total_T                           8454
FGC-FGC_SRR                               8453
PAQ_Total                                 8453
FGC-FGC_GSND                              8452
Physical-Diastolic_BP                     8452
Physical-Systolic_BP                      8448
Fitness_Endurance-Time                    8445
Name: count, dtype: int64

In [28]:
n_unique_outlier_rows = all_likelihood_outliers["index"].nunique()

print("Outlier values:", len(all_likelihood_outliers))
print("Unique outlier rows:", n_unique_outlier_rows)
print("Percentage of dataset:", round(n_unique_outlier_rows / len(df) * 100, 2), "%")

Outlier values: 270619
Unique outlier rows: 8460
Percentage of dataset: 100.0 %

In [31]:
c_values = [0.2, 0.5, 1, 2, 5, 10, 20, 50, 100]

sensitivity_results = []

for c in c_values:
    temp_outliers = []

    for col in X_likelihood.columns:
        out_col = likelihood_outliers_univariate(
            X_likelihood[col],
            lambda_par=0.3,
            c=c
        )

        if len(out_col) > 0:
            out_col["variable"] = col
            temp_outliers.append(out_col)

    if len(temp_outliers) > 0:
        temp_outliers = pd.concat(temp_outliers, ignore_index=True)
        n_outlier_values = len(temp_outliers)
        n_unique_rows = temp_outliers["index"].nunique()
    else:
        n_outlier_values = 0
        n_unique_rows = 0

    sensitivity_results.append({
        "c": c,
        "n_outlier_values": n_outlier_values,
        "n_unique_outlier_rows": n_unique_rows,
        "percentage_unique_rows": round(n_unique_rows / len(df) * 100, 2)
    })

sensitivity_df = pd.DataFrame(sensitivity_results)

sensitivity_df

       c  n_outlier_values  n_unique_outlier_rows  percentage_unique_rows
0    0.2            270619                   8460                  100.00
1    0.5            254225                   8460                  100.00
2    1.0            240846                   8460                  100.00
3    2.0            216531                   8451                   99.89
4    5.0             37377                   4791                   56.63
5   10.0               455                    352                    4.16
6   20.0               230                    170                    2.01
7   50.0               114                     87                    1.03
8  100.0                84                     70                    0.83